import numpy as np
import pandas as pd
import pytest

from football_pipeline.adapters.fs_wrapper import FakeFSLocal
from football_pipeline.adapters.io_wrapper import FakeIOWrapper, FileType
from football_pipeline.adapters.logger import FakeLogger
from football_pipeline.adapters.repo import Repo
from football_pipeline.adapters.time import fake_new_guid, fake_time_now
from football_pipeline.stages.bronze.bronze_pipe import run_bronze_pipe

DB = {
    FileType.YAML: {
        "path/to/config.yaml": {
            "save_root": "./data/01_bronze",
            "sources": {
                "teams": {"read_path": "./data/00_raw/teams/", "schema": "BronzeTeams"},
                "fixtures": {
                    "read_path": "./data/00_raw/fantasy_premierleague_com_api_fixtures/",
                    "schema": "BronzeFixture",
                },
                "players": {
                    "read_path": "./data/00_raw/elements/",
                    "schema": "BronzePlayer",
                },
                "stats_events": {
                    "read_path": "./data/00_raw/fantasy_premierleague_com_api_fixtures/",
                    "transform": "bronze_stats_event_transform",
                    "output_tables": {"stats": "BronzeStats", "events": "BronzeEvent"},
                },
            },
        },
    },
    FileType.PARQUET: {
        "./data/00_raw/teams/file_1.parquet": pd.DataFrame(
            [
                {
                    "code": 21,
                    "draw": 0,
                    "form": None,
                    "id": 19,
                    "loss": 0,
                    "name": "West Ham",
                    "played": 0,
                    "points": 0,
                    "position": 18,
                    "short_name": "WHU",
                    "strength": 3,
                    "team_division": None,
                    "unavailable": False,
                    "win": 0,
                    "strength_overall_home": 1075,
                    "strength_overall_away": 1075,
                    "strength_attack_home": 1050,
                    "strength_attack_away": 1050,
                    "strength_defence_home": 1100,
                    "strength_defence_away": 1100,
                    "pulse_id": 25,
                    "source_guid": "caee7be0-0fac-4870-89d4-c71b3ecb1294",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
                {
                    "code": 39,
                    "draw": 0,
                    "form": None,
                    "id": 20,
                    "loss": 0,
                    "name": "Wolves",
                    "played": 0,
                    "points": 0,
                    "position": 20,
                    "short_name": "WOL",
                    "strength": 3,
                    "team_division": None,
                    "unavailable": False,
                    "win": 0,
                    "strength_overall_home": 1070,
                    "strength_overall_away": 1085,
                    "strength_attack_home": 1050,
                    "strength_attack_away": 1050,
                    "strength_defence_home": 1090,
                    "strength_defence_away": 1120,
                    "pulse_id": 38,
                    "source_guid": "812c3875-dd46-4d75-958c-6f7c4c23a285",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
            ]
        ),
        "./data/00_raw/teams/file_2.parquet": pd.DataFrame(
            [
                {
                    "code": 3,
                    "draw": 0,
                    "form": None,
                    "id": 1,
                    "loss": 0,
                    "name": "Arsenal",
                    "played": 0,
                    "points": 0,
                    "position": 1,
                    "short_name": "ARS",
                    "strength": 5,
                    "team_division": None,
                    "unavailable": False,
                    "win": 0,
                    "strength_overall_home": 1300,
                    "strength_overall_away": 1375,
                    "strength_attack_home": 1340,
                    "strength_attack_away": 1400,
                    "strength_defence_home": 1260,
                    "strength_defence_away": 1350,
                    "pulse_id": 1,
                    "source_guid": "bf35f42d-b801-4694-a3e4-ca80c279cff6",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
                {
                    "code": 7,
                    "draw": 0,
                    "form": None,
                    "id": 2,
                    "loss": 0,
                    "name": "Aston Villa",
                    "played": 0,
                    "points": 0,
                    "position": 11,
                    "short_name": "AVL",
                    "strength": 3,
                    "team_division": None,
                    "unavailable": False,
                    "win": 0,
                    "strength_overall_home": 1145,
                    "strength_overall_away": 1185,
                    "strength_attack_home": 1150,
                    "strength_attack_away": 1170,
                    "strength_defence_home": 1140,
                    "strength_defence_away": 1200,
                    "pulse_id": 2,
                    "source_guid": "5c66f95d-9dab-42ef-8953-d83562c13c99",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
            ]
        ),
        "./data/00_raw/fantasy_premierleague_com_api_fixtures/file_1.parquet": pd.DataFrame(
            [
                {
                    "code": 2561895,
                    "event": 1,
                    "finished": True,
                    "finished_provisional": True,
                    "id": 1,
                    "kickoff_time": "2025-08-15T19:00:00Z",
                    "minutes": 90,
                    "provisional_start_time": False,
                    "started": True,
                    "team_a": 4,
                    "team_a_score": 2.0,
                    "team_h": 12,
                    "team_h_score": 4.0,
                    "stats": np.array(
                        [
                            {
                                "a": np.array(
                                    [{"element": 82, "value": 2}], dtype=object
                                ),
                                "h": np.array(
                                    [
                                        {"element": 381, "value": 1},
                                        {"element": 384, "value": 1},
                                        {"element": 385, "value": 1},
                                        {"element": 661, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "goals_scored",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 86, "value": 1},
                                        {"element": 93, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array(
                                    [
                                        {"element": 386, "value": 1},
                                        {"element": 392, "value": 1},
                                        {"element": 661, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "assists",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "own_goals",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "penalties_saved",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "penalties_missed",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 86, "value": 1},
                                        {"element": 97, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array(
                                    [{"element": 371, "value": 1}], dtype=object
                                ),
                                "identifier": "yellow_cards",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "red_cards",
                            },
                            {
                                "a": np.array(
                                    [{"element": 67, "value": 6}], dtype=object
                                ),
                                "h": np.array(
                                    [{"element": 366, "value": 1}], dtype=object
                                ),
                                "identifier": "saves",
                            },
                            {
                                "a": np.array(
                                    [{"element": 82, "value": 3}], dtype=object
                                ),
                                "h": np.array(
                                    [
                                        {"element": 661, "value": 2},
                                        {"element": 381, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "bonus",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 82, "value": 42},
                                        {"element": 86, "value": 23},
                                        {"element": 84, "value": 20},
                                        {"element": 93, "value": 12},
                                        {"element": 85, "value": 11},
                                        {"element": 67, "value": 10},
                                        {"element": 90, "value": 7},
                                        {"element": 96, "value": 3},
                                        {"element": 73, "value": 2},
                                        {"element": 100, "value": 2},
                                        {"element": 685, "value": 2},
                                        {"element": 72, "value": 1},
                                        {"element": 74, "value": -1},
                                        {"element": 97, "value": -1},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array(
                                    [
                                        {"element": 661, "value": 37},
                                        {"element": 381, "value": 36},
                                        {"element": 384, "value": 34},
                                        {"element": 385, "value": 29},
                                        {"element": 386, "value": 27},
                                        {"element": 387, "value": 17},
                                        {"element": 392, "value": 15},
                                        {"element": 382, "value": 14},
                                        {"element": 373, "value": 11},
                                        {"element": 366, "value": 8},
                                        {"element": 370, "value": 8},
                                        {"element": 374, "value": 6},
                                        {"element": 371, "value": 5},
                                        {"element": 388, "value": 4},
                                        {"element": 376, "value": -1},
                                        {"element": 372, "value": -3},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "bps",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 84, "value": 20},
                                        {"element": 85, "value": 19},
                                        {"element": 72, "value": 15},
                                        {"element": 73, "value": 9},
                                        {"element": 685, "value": 9},
                                        {"element": 86, "value": 7},
                                        {"element": 74, "value": 6},
                                        {"element": 82, "value": 5},
                                        {"element": 97, "value": 5},
                                        {"element": 93, "value": 4},
                                        {"element": 90, "value": 3},
                                        {"element": 77, "value": 2},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array(
                                    [
                                        {"element": 373, "value": 21},
                                        {"element": 387, "value": 11},
                                        {"element": 381, "value": 10},
                                        {"element": 382, "value": 9},
                                        {"element": 384, "value": 8},
                                        {"element": 374, "value": 7},
                                        {"element": 371, "value": 6},
                                        {"element": 386, "value": 6},
                                        {"element": 370, "value": 4},
                                        {"element": 392, "value": 3},
                                        {"element": 372, "value": 2},
                                        {"element": 376, "value": 1},
                                        {"element": 385, "value": 1},
                                        {"element": 388, "value": 1},
                                        {"element": 661, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "defensive_contribution",
                            },
                        ],
                        dtype=object,
                    ),
                    "team_h_difficulty": 3,
                    "team_a_difficulty": 4,
                    "pulse_id": 124791,
                    "source_guid": "68084892-15e7-4b34-8177-39309dd4a6b5",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
                {
                    "code": 2561896,
                    "event": 1,
                    "finished": True,
                    "finished_provisional": True,
                    "id": 2,
                    "kickoff_time": "2025-08-16T11:30:00Z",
                    "minutes": 90,
                    "provisional_start_time": False,
                    "started": True,
                    "team_a": 15,
                    "team_a_score": 0.0,
                    "team_h": 2,
                    "team_h_score": 0.0,
                    "stats": np.array(
                        [
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "goals_scored",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "assists",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "own_goals",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "penalties_saved",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array([], dtype=object),
                                "identifier": "penalties_missed",
                            },
                            {
                                "a": np.array(
                                    [{"element": 490, "value": 1}], dtype=object
                                ),
                                "h": np.array(
                                    [{"element": 58, "value": 1}], dtype=object
                                ),
                                "identifier": "yellow_cards",
                            },
                            {
                                "a": np.array([], dtype=object),
                                "h": np.array(
                                    [{"element": 38, "value": 1}], dtype=object
                                ),
                                "identifier": "red_cards",
                            },
                            {
                                "a": np.array(
                                    [{"element": 469, "value": 3}], dtype=object
                                ),
                                "h": np.array(
                                    [{"element": 33, "value": 3}], dtype=object
                                ),
                                "identifier": "saves",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 477, "value": 3},
                                        {"element": 469, "value": 2},
                                        {"element": 476, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array([], dtype=object),
                                "identifier": "bonus",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 477, "value": 33},
                                        {"element": 469, "value": 32},
                                        {"element": 476, "value": 30},
                                        {"element": 474, "value": 26},
                                        {"element": 478, "value": 26},
                                        {"element": 491, "value": 20},
                                        {"element": 487, "value": 15},
                                        {"element": 488, "value": 11},
                                        {"element": 486, "value": 10},
                                        {"element": 490, "value": 7},
                                        {"element": 485, "value": 4},
                                        {"element": 497, "value": 4},
                                        {"element": 489, "value": 3},
                                        {"element": 500, "value": 3},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array(
                                    [
                                        {"element": 33, "value": 29},
                                        {"element": 36, "value": 25},
                                        {"element": 40, "value": 25},
                                        {"element": 37, "value": 22},
                                        {"element": 59, "value": 19},
                                        {"element": 38, "value": 15},
                                        {"element": 58, "value": 13},
                                        {"element": 64, "value": 12},
                                        {"element": 54, "value": 10},
                                        {"element": 47, "value": 7},
                                        {"element": 48, "value": 5},
                                        {"element": 53, "value": 4},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "bps",
                            },
                            {
                                "a": np.array(
                                    [
                                        {"element": 474, "value": 11},
                                        {"element": 476, "value": 11},
                                        {"element": 490, "value": 9},
                                        {"element": 491, "value": 9},
                                        {"element": 488, "value": 8},
                                        {"element": 477, "value": 5},
                                        {"element": 478, "value": 4},
                                        {"element": 485, "value": 4},
                                        {"element": 487, "value": 4},
                                        {"element": 486, "value": 3},
                                        {"element": 489, "value": 2},
                                        {"element": 497, "value": 1},
                                    ],
                                    dtype=object,
                                ),
                                "h": np.array(
                                    [
                                        {"element": 59, "value": 14},
                                        {"element": 36, "value": 11},
                                        {"element": 58, "value": 11},
                                        {"element": 37, "value": 7},
                                        {"element": 47, "value": 7},
                                        {"element": 48, "value": 7},
                                        {"element": 54, "value": 7},
                                        {"element": 40, "value": 5},
                                        {"element": 64, "value": 5},
                                        {"element": 38, "value": 3},
                                    ],
                                    dtype=object,
                                ),
                                "identifier": "defensive_contribution",
                            },
                        ],
                        dtype=object,
                    ),
                    "team_h_difficulty": 3,
                    "team_a_difficulty": 3,
                    "pulse_id": 124792,
                    "source_guid": "6512b4ef-4c20-4e27-a337-fbf7aa0c4c01",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
            ]
        ),
        "./data/00_raw/elements/file_1.parquet": pd.DataFrame(
            [
                {
                    "can_transact": True,
                    "can_select": True,
                    "chance_of_playing_next_round": np.nan,
                    "chance_of_playing_this_round": np.nan,
                    "code": 154561,
                    "cost_change_event": 0,
                    "cost_change_event_fall": 0,
                    "cost_change_start": 3,
                    "cost_change_start_fall": -3,
                    "dreamteam_count": 1,
                    "element_type": 1,
                    "ep_next": "7.0",
                    "ep_this": "7.0",
                    "event_points": 6,
                    "first_name": "David",
                    "form": "6.0",
                    "id": 1,
                    "in_dreamteam": False,
                    "news": "",
                    "news_added": None,
                    "now_cost": 58,
                    "photo": "154561.jpg",
                    "points_per_game": "5.2",
                    "removed": False,
                    "second_name": "Raya Martín",
                    "selected_by_percent": "31.6",
                    "special": False,
                    "squad_number": None,
                    "status": "a",
                    "team": 1,
                    "team_code": 3,
                    "total_points": 52,
                    "transfers_in": 2163248,
                    "transfers_in_event": 99909,
                    "transfers_out": 838911,
                    "transfers_out_event": 13024,
                    "value_form": "1.0",
                    "value_season": "9.0",
                    "web_name": "Raya",
                    "region": 200.0,
                    "team_join_date": "2024-07-04",
                    "birth_date": "1995-09-15",
                    "has_temporary_code": False,
                    "opta_code": "p154561",
                    "minutes": 900,
                    "goals_scored": 0,
                    "assists": 0,
                    "clean_sheets": 7,
                    "goals_conceded": 3,
                    "own_goals": 0,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "yellow_cards": 1,
                    "red_cards": 0,
                    "saves": 16,
                    "bonus": 3,
                    "bps": 212,
                    "influence": "158.2",
                    "creativity": "10.2",
                    "threat": "0.0",
                    "ict_index": "16.8",
                    "clearances_blocks_interceptions": 9,
                    "recoveries": 85,
                    "tackles": 0,
                    "defensive_contribution": 0,
                    "starts": 10,
                    "expected_goals": "0.00",
                    "expected_assists": "0.04",
                    "expected_goal_involvements": "0.04",
                    "expected_goals_conceded": "5.73",
                    "influence_rank": 98,
                    "influence_rank_type": 13,
                    "creativity_rank": 340,
                    "creativity_rank_type": 3,
                    "threat_rank": 734,
                    "threat_rank_type": 86,
                    "ict_index_rank": 235,
                    "ict_index_rank_type": 13,
                    "corners_and_indirect_freekicks_order": np.nan,
                    "corners_and_indirect_freekicks_text": "",
                    "direct_freekicks_order": np.nan,
                    "direct_freekicks_text": "",
                    "penalties_order": np.nan,
                    "penalties_text": "",
                    "expected_goals_per_90": 0.0,
                    "saves_per_90": 1.6,
                    "expected_assists_per_90": 0.0,
                    "expected_goal_involvements_per_90": 0.0,
                    "expected_goals_conceded_per_90": 0.57,
                    "goals_conceded_per_90": 0.3,
                    "now_cost_rank": 107,
                    "now_cost_rank_type": 1,
                    "form_rank": 24,
                    "form_rank_type": 1,
                    "points_per_game_rank": 23,
                    "points_per_game_rank_type": 2,
                    "selected_rank": 8,
                    "selected_rank_type": 2,
                    "starts_per_90": 1.0,
                    "clean_sheets_per_90": 0.7,
                    "defensive_contribution_per_90": 0.0,
                    "source_guid": "c1d83f09-a27a-4701-84d5-44b6bda471ea",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
                {
                    "can_transact": True,
                    "can_select": True,
                    "chance_of_playing_next_round": np.nan,
                    "chance_of_playing_this_round": np.nan,
                    "code": 109745,
                    "cost_change_event": 0,
                    "cost_change_event_fall": 0,
                    "cost_change_start": -3,
                    "cost_change_start_fall": 3,
                    "dreamteam_count": 0,
                    "element_type": 1,
                    "ep_next": "1.0",
                    "ep_this": "1.0",
                    "event_points": 0,
                    "first_name": "Kepa",
                    "form": "0.0",
                    "id": 2,
                    "in_dreamteam": False,
                    "news": "",
                    "news_added": None,
                    "now_cost": 42,
                    "photo": "109745.jpg",
                    "points_per_game": "0.0",
                    "removed": False,
                    "second_name": "Arrizabalaga Revuelta",
                    "selected_by_percent": "0.5",
                    "special": False,
                    "squad_number": None,
                    "status": "a",
                    "team": 1,
                    "team_code": 3,
                    "total_points": 0,
                    "transfers_in": 7699,
                    "transfers_in_event": 218,
                    "transfers_out": 58522,
                    "transfers_out_event": 1159,
                    "value_form": "0.0",
                    "value_season": "0.0",
                    "web_name": "Arrizabalaga",
                    "region": 200.0,
                    "team_join_date": "2025-07-01",
                    "birth_date": "1994-10-03",
                    "has_temporary_code": False,
                    "opta_code": "p109745",
                    "minutes": 0,
                    "goals_scored": 0,
                    "assists": 0,
                    "clean_sheets": 0,
                    "goals_conceded": 0,
                    "own_goals": 0,
                    "penalties_saved": 0,
                    "penalties_missed": 0,
                    "yellow_cards": 0,
                    "red_cards": 0,
                    "saves": 0,
                    "bonus": 0,
                    "bps": 0,
                    "influence": "0.0",
                    "creativity": "0.0",
                    "threat": "0.0",
                    "ict_index": "0.0",
                    "clearances_blocks_interceptions": 0,
                    "recoveries": 0,
                    "tackles": 0,
                    "defensive_contribution": 0,
                    "starts": 0,
                    "expected_goals": "0.00",
                    "expected_assists": "0.00",
                    "expected_goal_involvements": "0.00",
                    "expected_goals_conceded": "0.00",
                    "influence_rank": 548,
                    "influence_rank_type": 75,
                    "creativity_rank": 534,
                    "creativity_rank_type": 62,
                    "threat_rank": 502,
                    "threat_rank_type": 49,
                    "ict_index_rank": 549,
                    "ict_index_rank_type": 75,
                    "corners_and_indirect_freekicks_order": np.nan,
                    "corners_and_indirect_freekicks_text": "",
                    "direct_freekicks_order": np.nan,
                    "direct_freekicks_text": "",
                    "penalties_order": np.nan,
                    "penalties_text": "",
                    "expected_goals_per_90": 0.0,
                    "saves_per_90": 0.0,
                    "expected_assists_per_90": 0.0,
                    "expected_goal_involvements_per_90": 0.0,
                    "expected_goals_conceded_per_90": 0.0,
                    "goals_conceded_per_90": 0.0,
                    "now_cost_rank": 609,
                    "now_cost_rank_type": 38,
                    "form_rank": 492,
                    "form_rank_type": 68,
                    "points_per_game_rank": 556,
                    "points_per_game_rank_type": 75,
                    "selected_rank": 240,
                    "selected_rank_type": 34,
                    "starts_per_90": 0.0,
                    "clean_sheets_per_90": 0.0,
                    "defensive_contribution_per_90": 0.0,
                    "source_guid": "abec2d06-d1c1-460a-8bd1-66fba733d88c",
                    "batch_guid": "d302c060-0868-48c4-9653-321daa6787f2",
                    "ingestion_datetime": "20251104_205809",
                },
            ]
        ),
    },
}


@pytest.mark.skip
def test_run_bronze_pipe():
    repo = Repo(
        io=FakeIOWrapper(DB),
        fs=FakeFSLocal(DB),
        logger=FakeLogger(__file__),
        time_func=fake_time_now,
        guid_func=fake_new_guid,
    )

    run_bronze_pipe("path/to/config.yaml", repo)

    _created_files = {
        k: v.to_dict("records")
        for k, v in repo.io.db.items()
        if k.startswith("./data/01_bronze")
    }
