endpoints:
  matches:
    keys: []
    path: https://fantasy.premierleague.com/api/fixtures/
  statics:
    keys:
    - element_types
    - elements
    - teams
    path: https://fantasy.premierleague.com/api/bootstrap-static/
save_root: "./data/00_raw"
