endpoints:
  matches:
    keys: []
    path: https://fantasy.premierleague.com/api/fixtures/
  statics:
    keys:
    - element_types
    - elements
    - teams
    path: https://fantasy.premierleague.com/api/bootstrap-static/
  element_summary:
    keys:
    - history
    - history_past
    path: https://fantasy.premierleague.com/api/element-summary/{id}/
save_root: "./data/00_raw"
