name: Run raw layer

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Print successfully run at 1am UTC
        run: echo "Successfully run"
