name: Run raw layer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  raw_layer:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync

      - name: run at 1am UTC
        run: |
          git status
          git pull origin main
          uv run ./src/football_pipeline/stages/pipe_001_raw.py --config-path ./configs/001_raw_layer.yaml

      - name: Checkout branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: commit and push data
        env:
          CI_COMMIT_MESSAGE: "run: raw layer"
          CI_COMMIT_AUTHOR: pipe_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git status
          git add data
          if ! git diff --cached --quiet; then
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi
